image: docker:latest

stages:
    - build

build:
    stage: build  
    allow_failure: false
    when: manual
    services:
        - docker:dind
    script:
        - docker build -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/myapi ./MyApi/
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
        - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/myapi
